// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_cQOem5mMttiZTmPnwjHDLemF9EWWYUQ',
    appId: '1:329887582191:web:a11742e2da64cf8aac181a',
    messagingSenderId: '329887582191',
    projectId: 'miniecomm-848f7',
    authDomain: 'miniecomm-848f7.firebaseapp.com',
    storageBucket: 'miniecomm-848f7.firebasestorage.app',
    measurementId: 'G-KTEREZDPB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC092j2hS17Mh4EQ38dp4gBb0shw7v6tZs',
    appId: '1:329887582191:android:01707da7159afdbdac181a',
    messagingSenderId: '329887582191',
    projectId: 'miniecomm-848f7',
    storageBucket: 'miniecomm-848f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwNmFd-YesEtYbWhKF4XZ3WknWBUrXLJ4',
    appId: '1:329887582191:ios:be5c49a789cceba6ac181a',
    messagingSenderId: '329887582191',
    projectId: 'miniecomm-848f7',
    storageBucket: 'miniecomm-848f7.firebasestorage.app',
    iosBundleId: 'com.example.miniecomm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwNmFd-YesEtYbWhKF4XZ3WknWBUrXLJ4',
    appId: '1:329887582191:ios:be5c49a789cceba6ac181a',
    messagingSenderId: '329887582191',
    projectId: 'miniecomm-848f7',
    storageBucket: 'miniecomm-848f7.firebasestorage.app',
    iosBundleId: 'com.example.miniecomm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_cQOem5mMttiZTmPnwjHDLemF9EWWYUQ',
    appId: '1:329887582191:web:97539e8b89472806ac181a',
    messagingSenderId: '329887582191',
    projectId: 'miniecomm-848f7',
    authDomain: 'miniecomm-848f7.firebaseapp.com',
    storageBucket: 'miniecomm-848f7.firebasestorage.app',
    measurementId: 'G-6ME5M2SX9S',
  );
}
